# Here is all the information about the defaults and .dat files

# Defaults file
# -------------
# 0 - EMPLOYEE_NUM - 2000  - Employee number, to be incremented as each new employee is added
# 1 - INVENTORY_NUM - 1000 - Inventory number, to be incremented with each new item added
# 2 - COMMISSION_RATE - 6%
# 3 - BONUS_THRESHOLD - $5,000
# 4 - COMMISSION_BONUS_AMT - 200
# 5 - Branch Locations [St. John's, Mt. Pearl, Carbonear, Bay Roberts, Northern Bay]
# 6 - REORDER_NUM - 10


# Employee Log
# ------------
# Format for the employee log
# Employee number [0], First name[1], Last name[2], Street address[3], City[4], Province[5], Postal code[6], Phone number[7], Date of hire[8], Branch[9], Title[10], Salary[11], Skills[12], Birthdate[13]


# Customer Log
# ------------
# Format for the Customer log
# Customer Number[0], First name[1], Last name[2], Street address[3], City[4], Province[5], Postal code[6], Phone number[7], Cell number[8], Date of birth[9], Branch number[10]


# Item Log
# ------------
# Format for the Item log
# Item Number[0], Item Description[1], Color[2], Size[3], Pattern[4], Type[5], Item cost[6], Retail price[7], QOH[8], Re-order point[9], Maximum level[10]

# Customer Purchase Log
# ------------
# Format for the Customer Purchase log
# Order Number[0], Order date[1], Customer Number[2], Item number[3], Item Description[4], Retail Price[5], Quantity Purchased[6], Subtotal[7], Order Total[8], Employee Number[9]